### ISSUE TITLE
`when defined(nimteropForceRebuild)` to bypass any caching

### ISSUE THREAD

**Issue by timotheecour** [nimterop/nimterop#108]
* `nim c -r -f main.nim` + detecting `when compileOption("assertions")` may not be good enough for checking whether we need to rebuild cached wrappers (including toast, if/when we choose to auto-rebuild it), eg in complex cases, this won't be enough (eg if `nimble test` itself calls `nim c -r twrapper.nim`, the `-f` is lost); there are always more situations

* ditto with `cDisableCaching()` inside nim code, user may not want to edit sources

instead the most fail-proof way is a  `when defined(nimteropForceRebuild)` symbol that we use to bypass cached things; if the user (say, temporrily) puts it in his `~/.config/nim/config.nims`, it'll apply to "everythng", ie, fail-proof

## note
address these after https://github.com/nimterop/nimterop/pull/113 is merged
```
  ``nim -f`` was broken prior to 0.19.4 but can also be used to flush the cached content.
``nim -f`` can also be used after Nim v0.19.4 to flush the cache.
```

**Comment by genotrance** [comment]
`nim -f` works reliably now, tabling unless there's a requirement for this.
