### ISSUE TITLE
Error when installing nimterop using nimble

### ISSUE THREAD

**Issue by dawkot** [nimterop/nimterop#121]
Commit `50f4d73db92d78474c66f2e7aebdb7cb8c7f4eef`

> Downloading https://github.com/genotrance/nimterop using git
>   Verifying dependencies for nimterop@0.1.0
>       Info: Dependency on regex@>= 0.10.0 already satisfied
>   Verifying dependencies for regex@0.10.1
>       Info: Dependency on unicodedb@>= 0.6.0 & < 0.7 already satisfied
>   Verifying dependencies for unicodedb@0.6.0
>       Info: Dependency on unicodeplus@>= 0.4.0 & < 0.5 already satisfied
>   Verifying dependencies for unicodeplus@0.4.0
>       Info: Dependency on unicodedb@>= 0.6 & < 0.7 already satisfied
>   Verifying dependencies for unicodedb@0.6.0
>       Info: Dependency on cligen@>= 0.9.17 already satisfied
>   Verifying dependencies for cligen@0.9.19
>  Installing nimterop@0.1.0
>    Building nimterop/nimterop/toast using c backend
>        Tip: 73 messages have been suppressed, use --verbose to show them.
>      Error: Build failed for package: nimterop
>         ... Details:
>         ... Execution failed with exit code 1
>         ... Command: "/home/dawkot/.nimble/bin/nim" c --noBabelPath -d:release --path:"/home/dawkot/.nimble/pkgs/regex-0.10.1"  --path:"/home/dawkot/.nimble/pkgs/unicodedb-0.6.0"  --path:"/home/dawkot/.nimble/pkgs/unicodeplus-0.4.0"  --path:"/home/dawkot/.nimble/pkgs/unicodedb-0.6.0"  --path:"/home/dawkot/.nimble/pkgs/cligen-0.9.19"  -o:"/tmp/nimble_31375/githubcom_genotrancenimterop/nimterop/toast" "/tmp/nimble_31375/githubcom_genotrancenimterop/nimterop/toast.nim"
>         ... Output: Hint: used config file '/home/dawkot/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
>         ... Hint: used config file '/home/dawkot/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
>         ... Hint: system [Processing]
>         ... Hint: widestrs [Processing]
>         ... Hint: io [Processing]
>         ... Hint: toast [Processing]
>         ... Hint: os [Processing]
>         ... Hint: strutils [Processing]
>         ... Hint: parseutils [Processing]
>         ... Hint: math [Processing]
>         ... Hint: bitops [Processing]
>         ... Hint: macros [Processing]
>         ... Hint: algorithm [Processing]
>         ... Hint: unicode [Processing]
>         ... Hint: pathnorm [Processing]
>         ... Hint: osseps [Processing]
>         ... Hint: posix [Processing]
>         ... Hint: times [Processing]
>         ... Hint: options [Processing]
>         ... Hint: typetraits [Processing]
>         ... Hint: strformat [Processing]
>         ... Hint: api [Processing]
>         ... Hint: setup [Processing]
>         ... Hint: git [Processing]
>         ... Hint: osproc [Processing]
>         ... Hint: strtabs [Processing]
>         ... Hint: hashes [Processing]
>         ... Hint: streams [Processing]
>         ... Hint: cpuinfo [Processing]
>         ... Hint: linux [Processing]
>         ... Hint: regex [Processing]
>         ... Hint: sets [Processing]
>         ... Hint: tables [Processing]
>         ... Hint: properties [Processing]
>         ... Hint: properties_data [Processing]
>         ... Hint: types [Processing]
>         ... Hint: types_data [Processing]
>         ... Hint: unicodeplus [Processing]
>         ... Hint: paths [Processing]
>         ... Hint: compat [Processing]
>         ... Hint: types [Processing]
>         ... Hint: time_t [Processing]
>         ... Setting up Git repo: https://github.com/tree-sitter/tree-sitter/
>         ... Pulling repository
>         ... Setting up Git repo: https://github.com/JuliaStrings/utf8proc
>         ... Pulling repository
>         ... Hint: c [Processing]
>         ... Setting up Git repo: https://github.com/tree-sitter/tree-sitter-c
>         ... Pulling repository
>         ... Hint: cpp [Processing]
>         ... Setting up Git repo: https://github.com/tree-sitter/tree-sitter-cpp
>         ... Pulling repository
>         ... Hint: ast [Processing]
>         ... Hint: sequtils [Processing]
>         ... Hint: getters [Processing]
>         ... Hint: dynlib [Processing]
>         ... Hint: globals [Processing]
>         ... Hint: plugin [Processing]
>         ... globals.nim(19, 5) Warning: Deprecated since v0.20, use `toHashSet`; toSet is deprecated [Deprecated]
>         ... globals.nim(26, 5) Warning: Deprecated since v0.20, use `toHashSet`; toSet is deprecated [Deprecated]
>         ... getters.nim(27, 28) Warning: Deprecated since v0.20, use `toHashSet`; toSet is deprecated [Deprecated]
>         ... Hint: grammar [Processing]
>         ... Hint: lisp [Processing]
>         ... Hint: cligen [Processing]
>         ... Hint: parseopt3 [Processing]
>         ... Hint: argcvt [Processing]
>         ... Hint: textUt [Processing]
>         ... Hint: terminal [Processing]
>         ... Hint: colors [Processing]
>         ... Hint: termios [Processing]
>         ... CC: lib
>         ... CC: parser
>         ... CC: parser
>         ... CC: scanner
>         ... Error: execution of an external compiler program 'gcc -c  -w -std=c11 -DUTF8PROC_STATIC -I/tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/include -I/tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src -I/tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/../../utf8proc -I/tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter_c/src -I/tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter_cpp/src -O3 -fno-strict-aliasing  -I'/home/dawkot/.choosenim/toolchains/nim-#devel/lib' -I/tmp/nimble_31375/githubcom_genotrancenimterop/nimterop -o /home/dawkot/.cache/nim/toast_r/lib.c.o /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/lib.c' failed with exit code: 1
>         ... In file included from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./get_changed_ranges.c:3:0,
>         ...                  from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/lib.c:10:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h:94:9: error: unknown type name ‘TSFieldMapEntry’
>         ...    const TSFieldMapEntry **start,
>         ...          ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h:95:9: error: unknown type name ‘TSFieldMapEntry’
>         ...    const TSFieldMapEntry **end
>         ...          ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h: In function ‘ts_language_field_map’:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h:97:71: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_count’
>         ...    if (self->version < TREE_SITTER_LANGUAGE_VERSION_WITH_FIELDS || self->field_count == 0) {
>         ...                                                                        ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h:103:3: error: unknown type name ‘TSFieldMapSlice’
>         ...    TSFieldMapSlice slice = self->field_map_slices[production_id];
>         ...    ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h:103:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_map_slices’
>         ...    TSFieldMapSlice slice = self->field_map_slices[production_id];
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h:104:17: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_map_entries’
>         ...    *start = &self->field_map_entries[slice.index];
>         ...                  ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h:104:42: error: request for member ‘index’ in something not a structure or union
>         ...    *start = &self->field_map_entries[slice.index];
>         ...                                           ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h:105:15: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_map_entries’
>         ...    *end = &self->field_map_entries[slice.index] + slice.length;
>         ...                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h:105:40: error: request for member ‘index’ in something not a structure or union
>         ...    *end = &self->field_map_entries[slice.index] + slice.length;
>         ...                                         ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././language.h:105:55: error: request for member ‘length’ in something not a structure or union
>         ...    *end = &self->field_map_entries[slice.index] + slice.length;
>         ...                                                        ^
>         ... In file included from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/lib.c:11:0:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c: In function ‘ts_language_field_count’:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:75:16: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_count’
>         ...      return self->field_count;
>         ...                 ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c: In function ‘ts_language_field_name_for_id’:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:84:16: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      return self->field_names[id];
>         ...                 ^
>         ... In file included from /usr/include/string.h:630:0,
>         ...                  from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./././././array.h:8,
>         ...                  from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././././subtree.h:11,
>         ...                  from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./././tree_cursor.h:4,
>         ...                  from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/././get_changed_ranges.h:8,
>         ...                  from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./get_changed_ranges.c:1,
>         ...                  from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/lib.c:10:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c: In function ‘ts_language_field_id_for_name’:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./language.c:97:31: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      switch (strncmp(name, self->field_names[i], name_length)) {
>         ...                                ^
>         ... In file included from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/lib.c:13:0:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./node.c: In function ‘ts_node_child_by_field_id’:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./node.c:464:9: error: unknown type name ‘TSFieldMapEntry’
>         ...    const TSFieldMapEntry *field_map, *field_map_end;
>         ...          ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./node.c:475:19: error: request for member ‘field_id’ in something not a structure or union
>         ...    while (field_map->field_id < field_id) {
>         ...                    ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./node.c:479:27: error: request for member ‘field_id’ in something not a structure or union
>         ...    while (field_map_end[-1].field_id > field_id) {
>         ...                            ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./node.c:489:28: error: request for member ‘child_index’ in something not a structure or union
>         ...        if (index < field_map->child_index) continue;
>         ...                             ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./node.c:492:20: error: request for member ‘inherited’ in something not a structure or union
>         ...        if (field_map->inherited) {
>         ...                     ^
>         ... In file included from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/lib.c:14:0:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./parser.c: In function ‘ts_parser__do_all_potential_reductions’:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./parser.c:876:47: error: ‘union <anonymous>’ has no member named ‘production_id’
>         ...                  .production_id = action.params.production_id,
>         ...                                                ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./parser.c: In function ‘ts_parser__advance’:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./parser.c:1334:60: error: ‘union <anonymous>’ has no member named ‘production_id’
>         ...              action.params.dynamic_precedence, action.params.production_id,
>         ...                                                             ^
>         ... In file included from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/lib.c:16:0:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./subtree.c: In function ‘ts_subtree__write_to_string’:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./subtree.c:855:11: error: unknown type name ‘TSFieldMapEntry’
>         ...      const TSFieldMapEntry *field_map, *field_map_end;
>         ...            ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./subtree.c:881:20: error: unknown type name ‘TSFieldMapEntry’
>         ...          for (const TSFieldMapEntry *i = field_map; i < field_map_end; i++) {
>         ...                     ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./subtree.c:882:17: error: request for member ‘inherited’ in something not a structure or union
>         ...            if (!i->inherited && i->child_index == structural_child_index) {
>         ...                  ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./subtree.c:882:33: error: request for member ‘child_index’ in something not a structure or union
>         ...            if (!i->inherited && i->child_index == structural_child_index) {
>         ...                                  ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./subtree.c:883:40: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...              child_field_name = language->field_names[i->field_id];
>         ...                                         ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./subtree.c:883:55: error: request for member ‘field_id’ in something not a structure or union
>         ...              child_field_name = language->field_names[i->field_id];
>         ...                                                        ^
>         ... In file included from /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/lib.c:17:0:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./tree_cursor.c: In function ‘ts_tree_cursor_current_field_id’:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./tree_cursor.c:267:11: error: unknown type name ‘TSFieldMapEntry’
>         ...      const TSFieldMapEntry *field_map, *field_map_end;
>         ...            ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./tree_cursor.c:276:19: error: request for member ‘inherited’ in something not a structure or union
>         ...          !field_map->inherited &&
>         ...                    ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./tree_cursor.c:277:18: error: request for member ‘child_index’ in something not a structure or union
>         ...          field_map->child_index == entry->structural_child_index
>         ...                   ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./tree_cursor.c:278:25: error: request for member ‘field_id’ in something not a structure or union
>         ...        ) return field_map->field_id;
>         ...                          ^
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./tree_cursor.c: In function ‘ts_tree_cursor_current_field_name’:
>         ... /tmp/nimble_31375/githubcom_genotrancenimterop/build/inc/treesitter/lib/src/./tree_cursor.c:289:32: error: ‘TSLanguage {aka const struct TSLanguage}’ has no member named ‘field_names’
>         ...      return self->tree->language->field_names[id];
>         ...                                 ^
>

**Comment by genotrance** [comment]
Yep - actively working on fixing this.

**Comment by genotrance** [comment]
Fixed
