### ISSUE TITLE
Need to cImport every included file manually

### ISSUE THREAD

**Issue by kaushalmodi** [nimterop/nimterop#123]
See https://gitlab.com/kaushalmodi/nimterop_include_issue/blob/master/README.org 

---

# Table of Contents

1.  [Steps to recreate the issue](#org4f1f24e)
2.  [Error](#orgc8ddb6f)
3.  [Nim version](#orgf3c8f54)

<a id="org4f1f24e"></a>

# Steps to recreate the issue

1.  Ensure that you have the latest nimterop installed
    -   Clone the nimterop repo, cd to it and do `nimble install`
2.  Clone this repo:

        git clone https://gitlab.com/kaushalmodi/nimterop_include_issue
3.  Build it:

        cd nimterop_include_issue
        nim c mean_func_1.nim

<a id="orgc8ddb6f"></a>

# Error

    Hint: time_t [Processing]
    Importing /home/kmodi/sandbox/nim/nimterop_include_issue/matlab_export/mean_func_1.h
    /home/kmodi/.nimble/pkgs/nimterop-0.1.0/nimterop/toast --pnim --preprocess /home/kmodi/sandbox/nim/nimterop_include_issue/matlab_export/mean_func_1.h
    mean_func_1.nim(31, 8) template/generic instantiation of `cImport` from here
    /home/kmodi/usr_local/apps/6/nim/devel/lib/core/macros.nim(552, 29) Error: undeclared identifier: 'struct0_T'

<a id="orgf3c8f54"></a>

# Nim version

    Nim Compiler Version 0.19.9 [Linux: amd64]
    Compiled at 2019-04-03
    Copyright (c) 2006-2019 by Andreas Rumpf

    git hash: dc2986789b703300ac0680a10004f77453b146c3
    active boot switches: -d:release

**Comment by kaushalmodi** [comment]
Here's the nim wrapper file from the above linked repo:

```nim
import nimterop/cimport
import os
from macros import getProjectPath

static:
  cDisableCaching()
  cDebug()

const
  includePath = getProjectPath() / "matlab_export"
static:
  doAssert fileExists(includePath / "rtwtypes.h")
  doAssert fileExists(includePath / "mean_func_1_types.h")
  doAssert fileExists(includePath / "mean_func_1.h")
  # Put cAddSearchDir in static block: https://github.com/nimterop/nimterop/issues/122
  cAddSearchDir(includePath)

# It will fail the compilation with:
#  Importing /home/kmodi/sandbox/nim/nimterop_include_issue/matlab_export/mean_func_1.h
#  /home/kmodi/.nimble/pkgs/nimterop-0.1.0/nimterop/toast --pnim --preprocess /home/kmodi/sandbox/nim/nimterop_include_issue/matlab_export/mean_func_1.h
#  mean_func_1.nim(21, 8) template/generic instantiation of `cImport` from here
#  /home/kmodi/usr_local/apps/6/nim/devel/lib/core/macros.nim(552, 29) Error: undeclared identifier: 'struct0_T'

# The problem is that it is not including the #include files from mean_func_1.h.
# If you manually import those included files (uncomment the next 2 lines), it will compile.
# cImport(cSearchPath("rtwtypes.h"))
# cImport(cSearchPath("mean_func_1_types.h"))
cImport(cSearchPath("mean_func_1.h"))
```

---

Even though we already discussed and confirmed this on Gitter/IRC, for the record, using `cImport(cSearchPath("mean_func_1.h"), recurse=true)` also did not help fix this.

**Comment by genotrance** [comment]
Just fixing this with latest commit. Note that 0.19.x has a static bug which prevents recurse from working in `cImport()`. At least on devel, this should now work.

**Comment by kaushalmodi** [comment]
@genotrance I just installed the latest Nim from devel and even uninstalled and reinstalled nimterop from HEAD, but still I get this error with the above recipe for error reproduction:

```
Importing /home/kmodi/sandbox/nim/nimterop_include_issue/matlab_export/mean_func_1.h
/home/kmodi/.nimble/pkgs/nimterop-#head/nimterop/toast --pnim --preprocess /home/kmodi/sandbox/nim/nimterop_include_issue/matlab_export/mean_func_1.h

{.experimental: "codeReordering".}
{.hint[ConvFromXtoItselfNotNeeded]: off.}
import
  nimterop / types

const
  headermean_func_1 {.used.} = "/home/kmodi/sandbox/nim/nimterop_include_issue/matlab_export/mean_func_1.h"
proc mean_func_1*(`in`: ptr struct0_T; `out`: ptr struct1_T) {.importc,
    header: headermean_func_1.}
mean_func_1.nim(30, 8) template/generic instantiation of `cImport` from here
/home/kmodi/usr_local/apps/6/nim/devel/lib/core/macros.nim(552, 29) Error: undeclared identifier: 'struct0_T'
```

**Comment by genotrance** [comment]
Recurse is still missing.

**Comment by kaushalmodi** [comment]
Thanks! It works after:

```diff
diff --git a/mean_func_1.nim b/mean_func_1.nim
index 2767286..1db5757 100644
--- a/mean_func_1.nim
+++ b/mean_func_1.nim
@@ -27,4 +27,4 @@ static:
 # If you manually import those included files (uncomment the next 2 lines), it will compile.
 # cImport(cSearchPath("rtwtypes.h"))
 # cImport(cSearchPath("mean_func_1_types.h"))
-cImport(cSearchPath("mean_func_1.h"))
+cImport(cSearchPath("mean_func_1.h"), recurse=true)
```
