### ISSUE TITLE
Request to dump out `cOverride` contents too in the `cDebug` output

### ISSUE THREAD

**Issue by kaushalmodi** [nimterop/nimterop#130]
Hello,

For an internal project at work, I need to save the `cDebug()` output and then save that to a nim file and slightly post-process it before I can use it.

I also need to have a `cOverride` block in my nimterop based wrapper.

But the content in `cOverride` block does not show up on stdout along with other stuff output by `cDebug()`. So I need to then manually prepend the `cDebug()` generated nim file with the `cOverride` stuff.

Right now, `cDebug()` outputs only:

```nim
# Overriding overriddenType1 overriddenType2 ..
```

Can you also output the contents under `cOverride` as-is when running `cDebug()`?

---

Related: https://github.com/nimterop/nimterop/issues/125

**Comment by genotrance** [comment]
I'm linking this to #133 where cOverride needs to be output inline instead of in place. As a result of that issue, this should also get resolved.

**Comment by genotrance** [comment]
The override branch attempts to fix this issue. Appreciate your feedback.

https://github.com/nimterop/nimterop/tree/override

**Comment by genotrance** [comment]
Fixed in https://github.com/nimterop/nimterop/commit/3ae716fff6e4b79257a6727eca794850a84f19b8.

**Comment by kaushalmodi** [comment]
Thanks. I confirm this fix in nimterop v0.3.3.
