### ISSUE TITLE
Feature: print toast parameters to console

### ISSUE THREAD

**Issue by mikra01** [nimterop/nimterop#132]
Hi, it would be nice to see toast's parameters for an easy invocation by hand - I tweaked cimport.getToast with a simple "echo cmd" before the gorgeEx invocation now as a workaround.

**Comment by genotrance** [comment]
This should be available already, but you need to use `cDebug()`.

https://travis-ci.org/nimterop/nimterop/jobs/556593589#L869

https://github.com/nimterop/nimterop/blob/master/nimterop/ast.nim#L144
