### ISSUE TITLE
List of examples

### ISSUE THREAD

**Issue by mantielero** [nimterop/nimterop#136]
As a suggestion, I would add to the main page a list with a few projects using nimterop, so that we can look to their wrappers and look for inspiration.

Thanks for your project

**Comment by genotrance** [comment]
Good idea - there's some in the tests directory but there are several more out there. I just need to compile the list.

Anyone who sees this issue and has or is making a wrapper based on nimterop, please share the url. Perhaps we can have a wiki page and it can be maintained by the community.

**Comment by genotrance** [comment]
This turned out to be much longer than I expected!

https://github.com/nimterop/nimterop/wiki/Wrappers
