### ISSUE TITLE
Allow for compilers other than gcc

### ISSUE THREAD

**Issue by liquid600pgm** [nimterop/nimterop#141]
Currently, it's not possible to specify the compiler using `--cc:<compiler>` unless it's `gcc` when using nimterop, because all commands called by it have `gcc` hardcoded into them.

Trying to compile with `clang` installed on Windows and `--cc:clang` results in an error, stating that `gcc` can't be found.

**Comment by genotrance** [comment]
All calls to `gcc` are of the form `getEnv("CC", "gcc")` which means you can override this using the $CC environment variable.

We could do `when defined(gcc)` which I know works but please let me know if `when defined(clang)` works with the `--cc:clang` flag on your system.

**Comment by liquid600pgm** [comment]
@genotrance `defined(clang)` returns `true` when `--cc:clang` is set. Nimterop also works properly when using clang.

**Comment by genotrance** [comment]
Made some changes to fix this, please test further and see what else we need for clang to work correctly.
