### ISSUE TITLE
[Help] FMU

### ISSUE THREAD

**Issue by mantielero** [nimterop/nimterop#143]
I am coming back to the following [topic](https://forum.nim-lang.org/t/5005#31379). It is not clear to me what I should do. I have wrapped **fmuTemplate.h** with nimterop.

Later, I should replace the C functions by Nim ones. 

But then, what should I do with **fmuTemplate.c**? (given the **fmuTemplate.h** is already its binding)

**Comment by genotrance** [comment]
I think you can just cCompile() fmuTemplate.c. Did you try that?

**Comment by mantielero** [comment]
I have the feeling that in this case I am not calling a C library from Nim. I think it is the other way around (no pro-dev speaking).

In the example:
```c
#include "fmuTemplate.h"
/*
 ...
define a few C functions which represent the model
...
*/
#include "fmuTemplate.c"
```
The functions defined in the middle are called from functions within **fmuTemplate.c**. And then everything should be compiled all together into a single library.

I have wrapped **fmuTemplate.h** already. What I want now is:
1. to be able to define the functions in the middle as Nim functions.
2. Those functions to be accessible to fmuTemplate.c.
3. To compile it into a single library.

Any suggestion is welcomed.

**Comment by genotrance** [comment]
cCompile will work because fmuTemplate.c => fmuTemplate.o which will get linked to the Nim binary and have access to the Nim functions.

Alternatively, you could include fmuTemplate.h and then use `nim c -c` to generate C source of your Nim functions which then can be compiled with fmuTemplate.c using C compiler. Else I'd ask someone on #nim for help.

**Comment by mantielero** [comment]
I am struggling with cCompile.

My current wrapper is:
```nim
import os
import nimterop/cimport

const
  base = currentSourcePath.parentDir() # / "build"

static:
  cDebug()
cDefine("DISABLE_PREFIX")
#cDefine("FMI2_Export")
#cDefine("FMI2_FUNCTION_PREFIX", "MyModel_")

cIncludeDir(base/"src/shared/include")
cIncludeDir(base/"src/shared")
cImport(base/"src/fmuTemplate.h", recurse=true)
#cImport("../shared/include/fmi2Functions.h")
cIncludeDir(base/"src")
cCompile(base/"src/fmuTemplate.c")
```

The compilation of **fmuTemplate.c** fails because it doesn't find some definitions. Those definitions are found in some headers referenced in **fmuTemplate.h**. 

I have put together the [source codes](https://drive.google.com/open?id=19ZsmgYKajzB4p5So6OJ_Ja8ug38cxC_Z) with what I am doing.

**Comment by genotrance** [comment]
It might be as simple as adding `#include "fmuTemplate.h"` to the top of `fmuTemplate.c`. Typically, gcc would see the .h #include, your code and .c #include and resolve everything. Since Nim is in the middle, you need to work a bit differently.

**Comment by mantielero** [comment]
After that, it fails the compilation because **fmuTemplate.c** is still expecting some "defines"  that should be present in the Nim part.

I will close it since I don't think this is a nimterop specific topic.

Thanks for your help.

**Comment by mantielero** [comment]
Just for the record, [here](https://forum.nim-lang.org/t/5005) I explain how I did it (with nimterop's help, of course).

**Comment by genotrance** [comment]
Awesome work! Please do share any feedback on things that could make nimterop better.
