### ISSUE TITLE
Doesn't work with inline enums in structs

### ISSUE THREAD

**Issue by PMunch** [nimterop/nimterop#147]
I'm trying to wrap a larger library and I have a structs that are defined like this:

```
struct some_struct {
    enum {one = 0, two, three} some_field;
};
```

The parser isn't able to understand these and simply doesn't generate any code for it, this causes the procedures it generates using this type to fail.

**Comment by genotrance** [comment]
Nimterop does not yet support nested structs.

https://github.com/nimterop/nimterop/issues/137

**Comment by genotrance** [comment]
This is implemented in ast2.

```nim
defineEnum(Enum_ah1)
const
  one* = (0).Enum_ah1
  two* = (one + 1).Enum_ah1
  three* = (two + 1).Enum_ah1

type
  some_struct* {.bycopy.} = object
    some_field*: Enum_ah1
```
