### ISSUE TITLE
Doesn't properly handle forward declarations

### ISSUE THREAD

**Issue by PMunch** [nimterop/nimterop#148]
When a structure is defined as empty at the beginning of a file and later defined as having data it only creates a `type somename = object {.bycopy.}` statement for the type without any of the fields. The below snippet is an example of such an error.

```
struct somename;

int helloworld(struct somename* input);

struct somename {
  int field1;
  int field2;
};
```

**Comment by genotrance** [comment]
This is functional with the new ast2 backend.

toast -f:ast2 -n gives you:

```nim
type
  somename* = object
    field1*: cint
    field2*: cint

proc helloworld*(input: ptr somename): cint
```

**Comment by PMunch** [comment]
Hmm, I worked around my issue by manually writing the whole library.. But maybe I should try to get it to work now with nimterop..

**Comment by genotrance** [comment]
ast2 is still under development but is being periodically pushed to master, feel free to play around with it. It is not yet versioned though so consider it ready to go when I close this issue.
