### ISSUE TITLE
cOverride content gets injected multiple items, once for each following cImport

### ISSUE THREAD

**Issue by kaushalmodi** [nimterop/nimterop#149]
Hello,

This is just a continuation of our discussion on https://gitter.im/nimterop/Lobby?at=5dbc3211bbdf5f17b420b24d.

With a pseudocode like:

```
cOverride:
  type
    Foo = enum
      fooOne
      fooTwo
..
cImport(..)
cImport(..)
cImport(..)
..
```

, I get an error like:

> ../nim/1.0.0/lib/core/macros.nim(562, 3) Error: redefinition of 'Foo'; previous declaration here: ../nim/1.0.0/lib/core/macros.nim(562, 3)

---

**OS**: RHEL 6.8
**Nim version**: 1.0.0
**nimterop version**: 0.3.2

**Comment by genotrance** [comment]
@kaushalmodi - please try branch `issue149` to see if it fixes your issue.

**Comment by kaushalmodi** [comment]
That fix works perfectly for me! Thank you.

---

*In parallel I added a "pre processor" to my flow that replaces `const .. foo = bar;` with `#define foo bar`, and now I do not need setting of those consts in the `cOverride`. So that seems to have "auto-fixed" the issue where the array size was left blank by nimterop.*
