### ISSUE TITLE
Ignores nimcache option

### ISSUE THREAD

**Issue by SolitudeSF** [nimterop/nimterop#153]
I have `nimcache` set to subdir in `/tmp/`, but nimterop uses default cache dir.

**Comment by slomp** [comment]
Related to that, the `NimblePath` option is also likely being ignored.
(there doesn't seem much that can be done at the moment, since nimble does not have access to the compiler flags)

**Comment by genotrance** [comment]
@Araq - is there a way to get the compiler flags passed during compile time?

**Comment by genotrance** [comment]
This is fixed in the `nimcfg` branch - requesting some testing before I merge. Thanks in advance.
