### ISSUE TITLE
getHeader should install binaries outside nimcache which can go away

### ISSUE THREAD

**Issue by genotrance** [nimterop/nimterop#154]
Need to use `make install` with `$PREFIX` set and install to XDG directory.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

`$XDG_DATA_HOME` seems most appropriate. Maps to `$HOME/.local/share` if not set. On OSX, `~/Library/`. On Windows, `%APPDATA%`.

cc: @disruptek

**Comment by genotrance** [comment]
Also need to add the version string into the path so that multiple versions of the same lib don't get stored in the same location.

**Comment by disruptek** [comment]
So, I want to make `getProjectCacheDir` also take a version?  Is there anything else we want to differentiate with?  Some other flag that might make it into a build recipe?  I'm thinking we hash all this stuff together.

**Comment by genotrance** [comment]
Definitely version - yes. Today if you specify a version and something else was processed before, nimterop won't know any better.

**Comment by genotrance** [comment]
Whenever possible, user should use the `-d:headerStd` method so that the binary uses a locally installed version of the library in question.

When this isn't possible, the next best option is to use `-d:headerStatic` so that the library gets statically linked to the binary and the location becomes irrelevant at runtime. This should fix nimph's issues with nimgit2 which supports `-d:git2Static`.

When libraries do not provide a static binary to link against like in nimbass, or it isn't the most prudent method like for say openssl, that's when we really run into this issue. Any library built by nimterop sits in `~/.cache` and could go away at any time. This is also more likely on Windows where there's no real standard location and building libs is the only alternative.

For nimbass, the [wrapper](https://github.com/genotrance/nimbass/blob/nimterop/nimbass/bass.nim#L59) avoids dynlib and instead expects the user to copy the binary over and set LD_LIBRARY_PATH. The [test](https://github.com/genotrance/nimbass/blob/nimterop/nimbass.nimble#L16) sets this up cross-platform but is effectively delegated to the wrapper writer.

One suggestion from @alaviss was to provide a path to `getHeader()` where the library would get copied and can be dynlib'd from there instead, perhaps a relative path if dynlib supports it. But nimterop already supports this, or at least don't prevent the user from doing that. `getHeader()` returns the library path in `headerLPath` and this can be copied in the wrapper.

I think what we need though is a recommendation or helper procs within nimterop to guide the user towards the most cross-platform and convenient solution.

**Comment by genotrance** [comment]
Following @alavis idea, adding `libdir` to `getHeader()`.

By default, `libdir` is set to the output directory where the program binary will be created. This is a change in behavior for existing wrappers but solves this issue without requiring wrapper writers to do anything special for shared libs.

There is an additional case with binarybuilder.org where the dynamic libs provided could depend on other .so files - e.g. libssh2.so depends on libmbedtls.so and others. As a part of this change, these dependency libs will also get copied over.

The values of `xxxLPath` and `xxxLDeps` will reflect this new location for shared libs.

Again, none of this is relevant to static libs which simply get linked into the executable.

**Comment by genotrance** [comment]
This is fixed in v0.6.0.
