### ISSUE TITLE
Function pointers with pointer return types don't get wrapped properly

### ISSUE THREAD

**Issue by liquid600pgm** [nimterop/nimterop#155]
Example:
```c
typedef char *(*my_func_pointer_t)(int x);
```
gets wrapped as:
```nim
type my_func_pointer_t* = proc (x: cint): cchar
```
The return type should be `cstring`:
```nim
type my_func_pointer_t* = proc (x: cint): cstring
```
The same happens with other types, eg. `void *` becomes no return type.

**Comment by genotrance** [comment]
This is functional with the new ast2 backend.

`toast -f:ast2 -n` gives you the correct result.
