### ISSUE TITLE
Pointer to function pointer is not handled correctly

### ISSUE THREAD

**Issue by genotrance** [nimterop/nimterop#156]
```c
  typedef struct txt_db_st {
      int (**qual) (OPENSSL_STRING *p);
  } TXT_DB;
```

`qual` is not handled correctly. From openssl/txt_db.h.

**Comment by arnetheduck** [comment]
also applies to function arguments, ie see https://github.com/arnetheduck/nim-sqlite3-abi/blob/04f5d5c96a9d35d067745db7c73baf3b062b9076/sqlite3_abi.nim#L11

**Comment by genotrance** [comment]
Original issue is functional with the new ast2 backend.

`toast -f:ast2 -n` gives you:

```nim
type
  txt_db_st* = object
    qual*: proc (p: ptr OPENSSL_STRING): cint

  TXT_DB* = txt_db_st
```

However, the sqlite example is broken since it is a proc param without a name (abstract_function_declarator). Need to add specific support for that.

```c
int sqlite3_bind_blob(sqlite3_stmt*, int, const void*, int n, void(*)(void*));
```

If it were a named param, it works.

```c
int sqlite3_bind_blob(sqlite3_stmt*, int, const void*, int n, void *abc(void*));
```
gives
```nim
proc sqlite3_bind_blob*(a1: ptr sqlite3_stmt; a2: cint; a3: pointer; n: cint;
                       abc: proc (a1: pointer): pointer): cint
```

**Comment by genotrance** [comment]
Added support for abstract_function_declarator in ast2. Output is now:

```nim
proc sqlite3_bind_blob*(a1: ptr sqlite3_stmt; a2: cint; a3: pointer; n: cint;
                       a5: proc (a1: pointer) {.cdecl.}): cint {.impaC.}
```
