### ISSUE TITLE
Nimterop should make it easier to find out order of importing headers

### ISSUE THREAD

**Issue by genotrance** [nimterop/nimterop#162]
Given a directory of headers, it isn't always possible to use `recurse` and call it a day. For example, in openssl, there's no single top level header that can be imported.

Need a way to identify the order in which headers should be best imported so that symbols are loaded in the right order.

This code helps identify it but need to see how it can be integrated and usable within nimterop.

```nim
import os, re, strutils

let
  base = "/usr/include/openssl"

var res: seq[string] = @[]

proc process(file: string, parent = "", depth = "") =
  let
    file = file.extractFilename()
  if not fileExists(base / file):
    return

  #echo depth & "Processing " & file

  let
    data = readFile(base / file)
  for inc in data.findAll(re"#[ ]*include[ ]?<(.*?)>"):
    var
      inc = inc.replace(re"#[ ]*include[ ]?<", "")[0 .. ^2]
    if "openssl" in inc:
      inc = inc[8 .. ^1]

      if inc == parent:
        continue

      if inc notin res:
        process(inc, file, depth & "  ")

  if file notin res:
    if parent.len == 0:
      #echo depth & "Adding " & file
      res.add file
    else:
      let idx = res.find(parent)
      if idx != -1:
        #echo depth & "Adding dep " & file
        res.insert(file, idx)
      else:
        #echo depth & "Appending dep " & file
        res.add file

for file in walkFiles(base / "*.h"):
  process(file)

for i in res:
  echo """
when fileExists(basePath/"$1"):
  cImport(basePath/"$1", dynlib="cryptoPath")
""" % i
```

cc @dizzyliam

**Comment by dizzyliam** [comment]
Code similar to this has been shown to improve the readability and performance of wrappers written with Nimterop ([https://github.com/genotrance/nimssl/pull/3](https://github.com/genotrance/nimssl/pull/3)). It could be implemented into Nimterop directly by adding a proc that takes a sequence of header files and runs cImport in the best order according to this algorithm.

**Comment by genotrance** [comment]
I think this has become moot after [multi-header](https://github.com/nimterop/nimterop/commit/f2870d8ba6fe9249f26d681b3f01cfb8b121d362) support was added. Simply add whichever headers are of interest and nimterop will generate the output without duplicates. Time will tell if it is good enough to solve this problem but at least [rsa.nim](https://github.com/nimterop/nimterop/blob/master/tests/rsa.nim) suggests it works.
