### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kobi2187** [nimterop/nimterop#164]
I don't know how to contact you, I have a question:
Can other languages (that their grammar exists in tree-sitter) be converted in a similar manner? Is tree-sitter's AST common to all languages, or is it specific to each one's idioms and constructs?
My thinking is c++ is pretty complex. Many libraries exist for it, but I assume higher level languages have higher quality code. 
Can your nimterop be leveraged to convert for example C#, go, ruby, or python? My guess is they are closer to Nim than c++ .
Is your project an automated binder, or an automated source code converter?
Thank you and sorry for the unconventional contact, Kobi

**Comment by genotrance** [comment]
No worries, I'm on #nim if you want to get in touch.

tree-sitter does enable creation of wrappers for Nim from other languages but the question is more on how to create C compatible dlls out of these language libraries. We rely on Nim's FFI after all. That's not how most Go or Rust libraries are typically consumed.

Nimterop sticks to wrapping, not outright conversion. It might be possible but not my focus.

**Comment by kobi2187** [comment]
ah, yes, I am thinking of creating code from tree-sitter's parsed AST, or maybe creating Nim AST from it, to then be output as nim code.
I was hoping to get instructions how to use their api, if indeed possible.
Thank you

**Comment by genotrance** [comment]
See `toast.nim:process()` where the source code is passed to tree-sitter and an AST is returned.

The AST is traversed in `ast.nim` recursively in `searchAst()`.

If you want to convert to Nim AST, you should look at c2nim which uses the compiler's `renderer.nim` to convert the AST to pure Nim. I went in a different direction with nimterop.

**Comment by kobi2187** [comment]
Awesome, thanks!
