### ISSUE TITLE
switch CI to azure-pipelines for much faster CI

### ISSUE THREAD

**Issue by timotheecour** [nimterop/nimterop#167]
* just like nim repo which switched to it and now benefits from faster CI turnaround (10 parallel builds) 
* it works across OS's too so only need 1 pipeline instead of 2 like currently (appveyor + travis)

**Comment by genotrance** [comment]
Travis works well enough for now and supports Windows too. Will consider this later if required.

**Comment by genotrance** [comment]
Travis now covers Windows for nimterop. One stop shop. Will look into pipes if speed gets worse as test cases increase.

https://travis-ci.org/github/nimterop/nimterop/builds/661183016
