### ISSUE TITLE
Skip `{.header.}` generation

### ISSUE THREAD

**Issue by arnetheduck** [nimterop/nimterop#169]
When the definition in nim is correct and simple enough, `{.header.}` is not needed - this is the case for most C code with simple proc's. 

It would be good to have an option so that the header directives are not used at all - this allows using a library without installing header files at all which simplifies deployment - specially with used in conjunction with `{.compile.}`.

**Comment by genotrance** [comment]
This is already implemented - if dynlib is used, no header pragma is generated.

See [nimgit2](https://travis-ci.org/genotrance/nimgit2/jobs/660827322#L2692) build log for an example. 

https://nimterop.github.io/nimterop/cimport.html#cImport.m%2C%2Cstring%2Cstring%2Cstring

**Comment by arnetheduck** [comment]
But I'd like to have no header and no dynlib: https://github.com/arnetheduck/nim-sqlite3-abi/blob/master/update.sh

the header stuff is not needed if the ABI is described well enough - by not having `{.header.}` there you also avoid having to modify the include search path.

**Comment by genotrance** [comment]
Okay, so essentially, a proc would only have {.importc.} and that's it. The actual library could be {.compiled.} in, or statically or dynamically linked. Types would be 100% Nim with no C equivalent at compile time.

I don't think we can simply remove header altogether and expect all wrappers to work and Nimterop may not know when this will work - should it just be a user specified third option?

Option 1 = no dynlib specified => importc + header
Option 2 = dynlib specified => importc + dynlib
Option 3 = noheader specified => importc

`cImport(header, noheader = true)`
`toast -H | --noheader`

**Comment by arnetheduck** [comment]
works for me, but above all, works for sqlite and all other c libraries that were actually designed with language interop in mind and don't do clever stuff. `{.importc.}` is all that is needed if the nim side is correct, for the vast majority of such libraries.

there are features missing in nim to express everything on the C side however - those cases might need `.header` but it's rare (usually compiler-specific attributes and the like, but also stuff like volatile and alignment)

**Comment by arnetheduck** [comment]
that sqlite abi package is a wonder to use - your app gets a controlled version of sqlite compiled in with no `dll` hell, no package management, no version issues or anything - and you don't need nimterop or any other dependencies installed - doesn't get easier than that, just import and use.

**Comment by genotrance** [comment]
I've implemented this in a branch, please try it out and see if it meets your needs. Seems to pass all my tests but they do not use every wrapped type and proc.

https://github.com/nimterop/nimterop/tree/issue169

I've made header opt in. This might break some existing wrapper out there but seems like it's worth being the default. 

Note that your wrapper has some types which won't work if used:

https://github.com/arnetheduck/nim-sqlite3-abi/blob/master/sqlite3_gen.nim#L3172

**Comment by arnetheduck** [comment]
just tested with sqlite3 - here's the diff I get, which looks sane:

```diff
 const
-  headersqlite3 {.used.} = "sqlite3.h"
 
   # 
   # ** 2001-09-15
@@ -2143,7 +2142,7 @@ type
   # ** This is legacy and deprecated.  It is included for historical
   # ** compatibility and is not documented.
   # 
-  sqlite3_callback* {.impsqlite3.} = proc(a1: pointer, a2: cint, a3: ptr cstring, a4: ptr cstring): cint {.cdecl.}
+  sqlite3_callback* = proc(a1: pointer, a2: cint, a3: ptr cstring, a4: ptr cstring): cint {.cdecl.}
 
   # 
   # ** CAPI3REF: OS Interface Open File Handle
@@ -2441,7 +2440,7 @@ type
   # ** any of these methods if the iVersion of the VFS is less than 3.
   # 
   sqlite3_vfs* {.incompleteStruct.} = object
-  sqlite3_syscall_ptr* {.impsqlite3.} = proc() {.cdecl.}
+  sqlite3_syscall_ptr* = proc() {.cdecl.}
   # Type 'sqlite3_vfs' skipped
   # Type 'sqlite3_vfs' skipped
   # Type 'sqlite3_vfs' skipped
@@ -2635,7 +2634,7 @@ type
   # ** The typedef is necessary to work around problems in certain
   # ** C++ compilers.
   # 
-  sqlite3_destructor_type* {.impsqlite3.} = proc(a1: pointer) {.cdecl.}
+  sqlite3_destructor_type* = proc(a1: pointer) {.cdecl.}
 
   # 
   # ** The interface to the virtual-table mechanism is currently considered
@@ -3169,7 +3168,7 @@ type
   # ** transaction that sees that historical version of the database rather than
   # ** the most recent version.
   # 
-  sqlite3_snapshot* {.importc: "struct sqlite3_snapshot", bycopy.} = object
+  sqlite3_snapshot* {.bycopy.} = object
     hidden*: array[48, cuchar]
 
   # 
@@ -3196,7 +3195,7 @@ type
   #  The double-precision datatype used by RTree depends on the
   # ** SQLITE_RTREE_INT_ONLY compile-time option.
   # 
-  sqlite3_rtree_dbl* {.impsqlite3.} = cdouble
+  sqlite3_rtree_dbl* = cdouble
 
   #  end of the 'extern "C"' block
   # ******* End of sqlite3rtree.h ********
@@ -3230,7 +3229,7 @@ type
   Fts5ExtensionApi* {.incompleteStruct.} = object
   Fts5Context* {.incompleteStruct.} = object
   Fts5PhraseIter* {.incompleteStruct.} = object
-  fts5_extension_function* {.impsqlite3.} = proc(pApi: ptr Fts5ExtensionApi, pFts: ptr Fts5Context, pCtx: ptr sqlite3_context, nVal: cint, apVal: ptr ptr sqlite3_value) {.cdecl.}
+  fts5_extension_function* = proc(pApi: ptr Fts5ExtensionApi, pFts: ptr Fts5Context, pCtx: ptr sqlite3_context, nVal: cint, apVal: ptr ptr sqlite3_value) {.cdecl.}
 
   # 
   # ** EXTENSION API FUNCTIONS
```

> Note that your wrapper has some types which won't work if used:

you're right, haven't tested that - won't work because? the abi looks ok, is it the name?

**Comment by genotrance** [comment]
Importc on types will instruct Nim to not create the type in the generated C and will fail when the C compiler is called.

**Comment by arnetheduck** [comment]
that "should" be fine as long as the type is correctly defined in nim (same fields in same order with same type etc so it has same memory layout) - and you don't include the header file (so you don't get a name conflict)

**Comment by genotrance** [comment]
Based on discussion in https://github.com/nimterop/nimterop/issues/202, omitting `{.header.}` is now opt out so we are reverting back to legacy behavior.

The `--noHeader` or `-H` flag can now be used to skip `{.header.}` pragma. The `--includeHeader` flag has been removed and `-H` is repurposed for `--noHeader`.

**Comment by genotrance** [comment]
A section has been added to the [README](https://github.com/nimterop/nimterop/blob/pragmas/README.md#header-vs-dynlib) to explain this further, feedback appreciated.
