### ISSUE TITLE
`const char* const*` type unhandled

### ISSUE THREAD

**Issue by awr1** [nimterop/nimterop#172]
```c
typedef struct SomeType {
  const char* const* x;
} SomeType;
```

When `toast` is run, `SomeType` is skipped.

**Comment by awr1** [comment]
Bodge:

```nim
cDefine("const", " ")
```

**Comment by genotrance** [comment]
What even is this type - `const char*` makes sense, but what's a `const char* const*`?

**Comment by awr1** [comment]
Constant pointer to constant string, I believe.

**Comment by awr1** [comment]
Found it in the Vulkan headers: https://github.com/KhronosGroup/Vulkan-Headers/blob/master/include/vulkan/vulkan_core.h#L2286

**Comment by genotrance** [comment]
This is fixed in ast2.
