### ISSUE TITLE
Empty struct typedef unhandled when names differ in typedef

### ISSUE THREAD

**Issue by awr1** [nimterop/nimterop#173]
Possibly related to #41 

```c
typedef struct A B;
typedef struct C* D;
```
when passed to `toast`, produces:
```nim
type
  B* {.impnimterop_const.} = A
  D* {.impnimterop_const.} = ptr C
```
Which is invalid Nim code, as `A` and `C` are undefined. 

Correct definitions should probably be `object` and `ptr object`.

**Comment by genotrance** [comment]
There's no way for nimterop to know whether A and C will be defined elsewhere or not. One option is to define A and C in a cOverride section. If there's many such things, using the `-s` flag on toast or pass flags = "-s" to the cImport call. This will create object stubs for all missing symbols.

**Comment by awr1** [comment]
Is there a good reason why `-s` is not default?

**Comment by genotrance** [comment]
For the same reason - you could have multiple cImport calls which invoke toast in sequence and toast cannot assume that preceding calls did not create these missing symbols.

**Comment by awr1** [comment]
I see. Thanks for clarifying.
