### ISSUE TITLE
[Feature] Ability to specify module for cPlugin

### ISSUE THREAD

**Issue by jyapayne** [nimterop/nimterop#181]
In my nim-sdl2 wrapper, it currently has the exact same cPlugin code for each sub-wrapper. I would love to have the ability to either specify a module path or a string containing the module code to cPlugin to cut out this duplication.

**Comment by genotrance** [comment]
I've added `cPluginPath()` for this - please see if it meets your needs. Feedback appreciated.

@alaviss @awr1

**Comment by jyapayne** [comment]
Ouu, nice! I will test it out! :D

**Comment by jyapayne** [comment]
@genotrance yep, works for me!

**Comment by jyapayne** [comment]
Hmm, one minor nitpick is to not import the `macros` and `nimterop / plugin` modules for the PluginPath. I say it's a minor nitpick because I just don't want to have a red underlined file in my project :P

**Comment by awr1** [comment]
If `cPlugin` was a `typed` macro, you could just do:

```nim
cPlugin: include pathToNimFile
```

(This would require a manual import of `macros` and `nimterop / plugin`, which would be a breaking change, so this is probably not ideal.)

**Comment by awr1** [comment]
>Hmm, one minor nitpick is to not import the macros and nimterop / plugin modules for the PluginPath. I say it's a minor nitpick because I just don't want to have a red underlined file in my project :P 

Maybe there should be a flag to disable auto-import.

**Comment by jyapayne** [comment]
> Maybe there should be a flag to disable auto-import (or have cPluginHelper look for these imports as a sign to not auto-import them)

I wouldn't mind the flag. It could be the default behavior to have it off for `cPluginPath`

**Comment by genotrance** [comment]
I agree it should not auto-import. It is only for convenience for cPlugin but difference could throw people off. Should we detect this? Will be fragile though.

**Comment by jyapayne** [comment]
IMO, no auto detection. Like you said it would be super brittle.

**Comment by genotrance** [comment]
Ok have pushed an update where it is not auto imported.

https://github.com/nimterop/nimterop/compare/cpluginpath

Let me know if we need anything else, will merge tomorrow.

**Comment by jyapayne** [comment]
👍 Looks good to me
