### ISSUE TITLE
[Feature] toCamelCase(), toPascalCase()

### ISSUE THREAD

**Issue by awr1** [nimterop/nimterop#187]
A lot of C libraries use `snake_case` for their identifiers (for functions and/or types) which contradicts Nim's style guide (NEP-1) so I think a small `"identutils"` module to be imported in `cPlugin` bodies containing funcs like `toCamelCase()`, `toPascalCase()` for library implementers would be useful (and also pretty easy to add).

**Comment by genotrance** [comment]
I think this can be better handled by using [anycase](https://github.com/lamartire/anycase). Simply nimble install it and import it within cPlugin.
