### ISSUE TITLE
toast - problem recursing

### ISSUE THREAD

**Issue by mantielero** [nimterop/nimterop#188]
Probably this is not a bug and this is just me misusing nimterop.

I am trying to wrap [MLT Framework](https://github.com/mltframework/mlt). The include files are under `src/framework/`, where the file [mlt.h](https://github.com/mltframework/mlt/blob/master/src/framework/mlt.h) is a reference to the other headers. But when I run:
```
$ toast -pnrks -f:ast2 -l libmlt.so -I./ mlt.h
# Generated at 2020-04-16T18:18:17+02:00
# Command line:
#   /home/jose/.nimble/pkgs/nimterop-#head/nimterop/toast -pnrks -f:ast2 -l libmlt.so -I./ mlt.h

{.hint[ConvFromXtoItselfNotNeeded]: off.}

import nimterop/types


{.pragma: impmlt, importc.}
{.pragma: impmltC, impmlt, cdecl, dynlib: libmlt.so.}
```
Is this a bug or am I missing something in the command line?

Regards

**Comment by genotrance** [comment]
Quick answer, provide a full path to mlt.h, recurse looks for paths in the preprocessor output for files to include so full path is needed to get it right.

```
`pwd`/mlt.h
```

I will look into improving this, thanks for the report.

**Comment by mantielero** [comment]
Really surprised about how well it has worked. Excellent work. Congratulations. I only had to add the library name but I will file an issue for that.

**Comment by genotrance** [comment]
I'll keep this open to track that I need to fix the path issue.
