### ISSUE TITLE
toast - problem adding the dynamic library

### ISSUE THREAD

**Issue by mantielero** [nimterop/nimterop#189]
When I do:
```
$ toast -pnrks -f:ast2 -l libmlt.so -I./ `pwd`/mlt.h
```
It fails showing many errors. I have tried: `-l="libmlt.so"` and `-llibmlt.so`.

I finally added manually. 

Is this a bug, or should I provide the libName in a different way?

**Comment by genotrance** [comment]
`-l` or `--dynlib` has to be the name of the variable that contains the library name. So you would have to add:

`const libname = "libmlt.so"` and set `-llibname` to toast.

See https://nimterop.github.io/nimterop/cimport.html#cImport.m%2C%2Cstring%2Cstring%2Cstring
