### ISSUE TITLE
Simple examples

### ISSUE THREAD

**Issue by filcuc** [nimterop/nimterop#194]
I wanted to use this for wrapping libSDL2 in order to build/statically and automatically but failed. 
It seems there's to much magic going on or maybe i just miss some simple examples for getting started :)

**Comment by jyapayne** [comment]
@filcuc I'm currently working on this with this repo: https://github.com/jyapayne/nim-sdl2

There is indeed a lot of magic going on and this lib has a learning curve. @genotrance and I would be happy to hear what points don't make sense and what you've tried to get to work.

**Comment by jyapayne** [comment]
Also you can look at this page for some examples: https://github.com/nimterop/nimterop/wiki/Wrappers.

Some of them are quite simple :)

**Comment by genotrance** [comment]
Hopefully the latest README has a bit more info to clarify how to use nimterop but the best resource is to check the existing wrappers. Also, please feel free to drop by #nim on IRC or the nimterop gitter room if you have specific questions, will be happy to help.
