### ISSUE TITLE
[Feature] Skip type definition and replace

### ISSUE THREAD

**Issue by jyapayne** [nimterop/nimterop#196]
There are a few instances in which I would like to skip the type definition because it's just an alias to already defined Nim types.

For example, in SDL2, there is a section of types like:

```c
typedef uint8_t Uint8;
```

which translates to:

```nim
type Uint8* = uint8
```

But I would like to skip the type definition above, and for every symbol `Uint8` that appears elsewhere in the code, replace it with `uint8` to make it feel more "Nim like".

**Comment by genotrance** [comment]
We could add a cPlugin capability to extend the gTypeMap table.

**Comment by genotrance** [comment]
Keeping it simpler and adding a `--typeMap | -T` option to toast for this.
