### ISSUE TITLE
Question about static linking a library

### ISSUE THREAD

**Issue by richard-ramos** [nimterop/nimterop#211]
Hello, not sure if this is the right platform to ask questions, but here it goes: 

I'm currently working on a wrapper for SQLCipher that can be seen here: https://github.com/status-im/nim-sqlcipher-abi, and I have a question with regards to linking a static library:

I generate libcrypto.a in this step: https://github.com/status-im/nim-sqlcipher-abi/blob/master/build_dependencies.nims#L14 which is executed by nimble before install, and afterwards, I link it here: https://github.com/status-im/nim-sqlcipher-abi/blob/master/wrap.nim#L35 in order to generate the wrapper.

However, when I want to use the wrapper, I still have to link the library as seen here for it to work: https://github.com/status-im/nim-sqlcipher-abi/blob/master/test/main.nim#L9 . Is there a way to indicate nimterop to add that `{.passL.}` to the generated wrapper so I do not have to link it manually whenever I import the generated wrapper?

Thanks in advance for any tip for solving this issue!

**Comment by genotrance** [comment]
Hello @richard-ramos, looking at your work, the main answer to your question is [this](https://github.com/status-im/nim-sqlcipher-abi/blob/master/gen-wrapper.sh#L4) step. You are writing the output wrapper into `sqlcipher_abi.nim`. If you check the contents of that file, there isn't a `{.passL.}` in that so when it is imported into `main.nim`, you need to add `{.passL.}` again.

Also, everything in `build_dependencies.nims` can be done with [getHeader()](https://nimterop.github.io/nimterop/build.html). That way, you only have wrap.nim and don't need any of the other artifacts. Come on https://gitter.im/nimterop/Lobby if you have any questions.

**Comment by richard-ramos** [comment]
Hi @genotrance! thanks for the tips! I ended up doing the changes as seen here: https://github.com/status-im/nim-sqlcipher/blob/master/src/sqlcipher/sqlite.nim
