### ISSUE TITLE
[Question] C++ status

### ISSUE THREAD

**Issue by mantielero** [nimterop/nimterop#214]
What is the level of C++ support? Is there a good example somewhere about how to wrap C++ libraries?

**Comment by genotrance** [comment]
C++ is not supported by `toast` as of today but there are plans to get to it once C works seamlessly with `-f:ast2`. There's still some open items but it does not seem like a dream anymore. Main focus right now is to address all issues and limitations as reports come in. Once that stabilizes, C++ investigations will start.

You can use `c2nim` as a backend with `c2nImport()` if that helps for the near term.
