### ISSUE TITLE
deal with `__INCLUDE_LEVEL__`

### ISSUE THREAD

**Issue by derekdai** [nimterop/nimterop#224]
There is no way to get pass following check in nim
```
#if defined(__INCLUDE_LEVEL__) && __INCLUDE_LEVEL__ <= 1
#  error "Do not include _sd-common.h directly; it is a private header."
#endif
```

**Comment by genotrance** [comment]
Can you please provide some more detail? Does `cDefine()` or `{.passC.}` not work?

**Comment by derekdai** [comment]
`cDefine()` can handle the `__INCLUDE_LEVEL__` problem, thanks!
