### ISSUE TITLE
deal with proc overloading

### ISSUE THREAD

**Issue by derekdai** [nimterop/nimterop#225]
If I remove prefix from functions below become three `unref()` but with different signature, nimterop still treat it as duplicated and only first (`sd_bus_unref()`) will be keep
```
sd_bus *sd_bus_unref(sd_bus *bus);
sd_bus_message* sd_bus_message_unref(sd_bus_message *m);
sd_bus_track* sd_bus_track_unref(sd_bus_track *track);
```

**Comment by genotrance** [comment]
This is similar to https://github.com/nimterop/nimterop/issues/142.

**Comment by derekdai** [comment]
You are right.
