### ISSUE TITLE
Do not type unnamed enums

### ISSUE THREAD

**Issue by zacharycarter** [nimterop/nimterop#236]
When an unnamed enum is encountered, nimterop will generate a type for it. If one of the enum values is used to define the size of an array, then any use of the subscript operator will require an ordinal to be explicitly converted to this enum type. 

For instance (from sokol_gfx.h) - 

```
enum {
    SG_INVALID_ID = 0,
    SG_NUM_SHADER_STAGES = 2,
    SG_NUM_INFLIGHT_FRAMES = 2,
    SG_MAX_COLOR_ATTACHMENTS = 4,
    SG_MAX_SHADERSTAGE_BUFFERS = 8,
    SG_MAX_SHADERSTAGE_IMAGES = 12,
    SG_MAX_SHADERSTAGE_UBS = 4,
    SG_MAX_UB_MEMBERS = 16,
    SG_MAX_VERTEX_ATTRIBUTES = 16,      /* NOTE: actual max vertex attrs can be less on GLES2, see sg_limits! */
    SG_MAX_MIPMAPS = 16,
    SG_MAX_TEXTUREARRAY_LAYERS = 128
};

...

typedef struct sg_pass_action {
    uint32_t _start_canary;
    sg_color_attachment_action colors[SG_MAX_COLOR_ATTACHMENTS];
    sg_depth_attachment_action depth;
    sg_stencil_attachment_action stencil;
    uint32_t _end_canary;
} sg_pass_action;
```

Nimterop will generate some enum like - 

```
defineEnum(Enum_sgh1)

const
  SG_MAX_COLOR_ATTACHMENTS = (4).Enum_sgh1
```

When I want to access an element in `sg_color_attachment_action_colors` I'll have to do something like `sg_color_attachment_action_colors[Enum_sgh1(0)]`

It'd be better if these were just treated as defines. Apparently converters don't work either - the conversion must be explicit.

**Comment by genotrance** [comment]
This should be fixed in v0.6.1.
