### ISSUE TITLE
Nimterop should not define type for anonymous struct inside union

### ISSUE THREAD

**Issue by zacharycarter** [nimterop/nimterop#237]
If you encounter something like - https://github.com/septag/rizz/blob/39d4d52e6dfb2181fe5ee19090c9b079e823eefb/include/sx/math.h#L60-L67

Nimterop will generate something like - 
```
Type_rizzh2* {.bycopy, imprizzHdr, importc: "struct Type_rizzh2".} = object
    x*: cfloat
    y*: cfloat

  sx_vec2* {.union, bycopy, imprizzHdr, importc: "union sx_vec2".} = object
    a1*: Type_rizzh2
    f*: array[2, cfloat]
```

Which causes several issues. If you have an object of that type in C - you can access the fields in the anonymous struct simply by their name - so `vec2.x`

The generated Nim code should follow the same pattern, and thus generate an object with the following definition:
```
type
  sx_vec2* {.union, bycopy, imprizzHdr, importc: "union sx_vec2".} = object
    x*: float32
    y*: float32
    f*: array[2, cfloat]
```

I've tested this and all three fields are accessible and memory is overlaid as expected. Essentially the anonymous struct should be ignored, and its fields should be included in the Nim union type.

**Comment by genotrance** [comment]
This should be fixed in v0.6.1.
