### ISSUE TITLE
const after type in variable declaration causes nimterop to fail

### ISSUE THREAD

**Issue by zacharycarter** [nimterop/nimterop#238]
Example here - https://github.com/septag/rizz/blob/master/src/sx/3rdparty/mattias/strpool.h#L37

Causes - 

`Error: unhandled exception: getters.nim(187, 12) `name.nBl` Blank identifier error [AssertionDefect] [AssertionDefect]`

**Comment by genotrance** [comment]
Needs to be mapped to `let` since extern const but currently Nim doesn't allow importc for `let` (might be in devel).

For now, mapping it to `var`, needs to eventually become `let`.
