### ISSUE TITLE
missing features

### ISSUE THREAD

**Issue by timotheecour** [nimterop/nimterop#24]
## C features
- [ ] handling nested struct
* maybe relevant: [[TODO] Nim should allow nested types · Issue #7449 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/7449)

## C++ features
- [ ] template, simple case:
`template<typename T> class Foo{}; typedef Foo<int> FooInt `

**Comment by genotrance** [comment]
Nested structs can be tracked in https://github.com/nimterop/nimterop/issues/137.

C++ is further ahead and is a long list of requirements. Closing this issue for now.
