### ISSUE TITLE
How do I make libtorch/Pytorch work with nimterop?

### ISSUE THREAD

**Issue by mritunjaymusale** [nimterop/nimterop#247]
I have moved the libtorch folder to my project directory(where my main.nim exists) how do I go on about including pytorch from it's C++ state into nim using your tool. My intention is to use Nim with Pytorch's C++ backend for easy DL support for nim.
Also I am new to nim and there weren't any tutorials on how to use nimterop for large libraries like torch, hence I raised the issue.

**Comment by genotrance** [comment]
libtorch is a C++ project and nimterop doesn't yet support C++ syntax. You might want to try [c2nim](https://github.com/nim-lang/c2nim). 

You can also check out [nimtorch](https://github.com/sinkingsugar/nimtorch) for what it provides.
