### ISSUE TITLE
Windows error in toast.exe: "[Cannot find] libgcc_s_seh-1.dll"

### ISSUE THREAD

**Issue by akavel** [nimterop/nimterop#248]
When trying to build choosenim, I'm getting a Windows error in `toast.exe` about missing `libgcc_s_seh-1.dll`. (The error message was localized to my language by Windows, so I can't provide a verbatim English text.)

The stacktrace is:

```
        ... # Including library C:\Users\Mateusz\.choosenim\toolchains\mingw64\x86_64-w64-mingw32\lib\libiconv.a
        ... # Overriding stat dev_t mode_t
        ... # Overriding BY_HANDLE_FILE_INFORMATION
        ... # Importing "C:\Users\Mateusz\nimcache\nimterop\nimarchive\libarchive\LibArchive\include\archive.h, C:\Users\Mateusz\nimcache\nimterop\nimarchive\libarchive\LibArchive\include\archive_entry.h"
        ... stack trace: (most recent call last)
        ... C:\Users\Mateusz\.nimble\pkgs\nimterop-0.6.8\nimterop\cimport.nim(632, 23) cImport
        ... C:\Users\Mateusz\.nimble\pkgs\nimterop-0.6.8\nimterop\cimport.nim(138, 11) getToast
        ... C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\system\assertions.nim(29, 26) failedAssertImpl
        ... C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\system\assertions.nim(22, 11) raiseAssert
        ... C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\system\fatal.nim(49, 5) sysFatal
        ... C:\Users\Mateusz\.nimble\pkgs\nimarchive-0.5.2\nimarchive\archive.nim(61, 10) template/generic instantiation of `cImport` from here
        ... C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\system\fatal.nim(49, 5) Error: unhandled exception: C:\Users\Mateusz\.nimble\pkgs\nimterop-0.6.8\nimterop\cimport.nim(138, 16) `false`
        ...  [AssertionError]
```

This is making it difficult for me to debug [an issue in choosenim](https://github.com/dom96/choosenim/issues/210#issuecomment-668074177) 😔 ; no idea how to work around this for now 🥺

**Comment by genotrance** [comment]
Sorry missed the original issue with choosenim - I'll try this in the morning.

Did you by any chance change your mingw install between installing nimterop and testing choosenim?

**Comment by akavel** [comment]
```
C:\prog\tmm>gcc --version
gcc.exe (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

My gcc seems to come from `c:\Users\Mateusz\.nimble\bin\gcc.exe`, and there seems to be no such DLL there indeed. This makes me think, that I always used the C backend of Nim, so if toast uses the C++ backend, maybe there's something tricky about that? I don't think the C backend would need SEH?

**Comment by genotrance** [comment]
Ah, this is an issue - choosenim simply creates shims of gcc binaries in `~/.nimble/bin` so the DLLs don't end up in the path.

@dom96 - any suggestions on what to do here?

**Comment by dom96** [comment]
Can you elaborate on what the problem is? Where are the DLLs? Which exe is loading them?

**Comment by genotrance** [comment]
gcc links the toast binary with libgcc which is loaded at runtime. Since choosenim installs gcc shims in `~/.nimble/bin` and does not add the `mingw64\bin` directory to the path, the dll is not found.

Effectively, mingw ships with a bunch of dlls which are not added to path when installed by choosenim.

**Comment by dom96** [comment]
hm, but on Windows shouldn't the DLLs be loaded anyhow? The rule is DLLs in PATH followed by DLLs beside the .exe, no? Is the shim interfering with this?

**Comment by genotrance** [comment]
The DLL in question - `libgcc_s_seh-1.dll` is in the mingw distribution and is not found at tool runtime. It is required by `nimterop\toast.exe` so isn't in the same directory. Basically, I need to see if toast can statically compile in libgcc to avoid this issue but it will affect others as well since the way we install mingw with choosenim, we shim gcc, g++, etc. and the DLLs aren't added to the path for tools to use at runtime.

**Comment by dom96** [comment]
So it is toast.exe that expects this DLL to be in the PATH. I don't really see a way to resolve this. Even without shims this wouldn't be resolvable, and copying all the exes/dlls from mingw into ~/.nimble/bin seems like a bad approach.

**Comment by akavel** [comment]
@genotrance is toast built with `nim cpp`? if yes, does it have to, can't it be switched to `nim c`? it seems to me that it's possibly `nim cpp` which introduces this dependency?

@dom96 I believe this basically currently makes choosenim not support `nim cpp` on Windows - i.e. binaries built with `nim cpp` won't be able to run unless users know that those cryptic errors mean they need to add MinGW's bin dir to PATH by hand...

**Comment by dom96** [comment]
> @dom96 I believe this basically currently makes choosenim not support nim cpp on Windows - i.e. binaries built with nim cpp won't be able to run unless users know that those cryptic errors mean they need to add MinGW's bin dir to PATH by hand...

How so? Are you implying that nimterop is a hard dependency on `nim cpp`? If so then that's worrying.

**Comment by genotrance** [comment]
toast contains C++ code, hence the cpp. Even if you avoid that, there's still C++ code that gcc will link.

Issue only occurs if choosenim installs mingw. If mingw is preinstalled globally and in path, this isn't an issue.

**Comment by dom96** [comment]
What do you suggest we do here? There are only two things I can think of:

* Copy all of mingw's bin dir to ~/.nimble/bin
* Expose some way for packages like nimterop to find where the choosenim-installed mingw is so they can add it to their PATH.

I'm not super happy with either.

**Comment by genotrance** [comment]
I'm fixing toast by setting `-static` - that way, the binary won't need the DLLs in path. However, we need to figure this out for choosenim as well.
