### ISSUE TITLE
Support custom build

### ISSUE THREAD

**Issue by demotomohiro** [nimterop/nimterop#253]
I want to use [libnice](https://libnice.freedesktop.org) from Nim and tried to wrap it with `getHeader` macro but I got error because libnice uses neither autoconf nor cmake.
libnice uses only [Meson Build System](https://mesonbuild.com).
I think allowing user to write custom build code would be better than adding Meson build system support to Nimterop because meson is not widely used like autoconf or cmake and we can still build C libraries even if they use neither autoconf nor cmake.

How about to add `btCustom` to `BuildType` enum type and let user implement `customBuildLibrary` proc that build the library and `getHeader` macro calls it when `btCustom` is specified to `buildTypes` parameter?
Or add a new macro `getHeaderCustomBuild` that works like `getHeader` but requires a proc that build the library?

**Comment by genotrance** [comment]
getHeader has a xxxPreBuild hook which can be used to do this. It gets called after downloading the library but before build and search for binaries so can be used to call any custom commands you need.

**Comment by demotomohiro** [comment]
Thank you!

I built libnice in `nicePreBuild` proc and `getHeader` macro worked without error.
I didn't know `buildLibrary` proc skip cmake/autoconf build process if I built the library in `xxxPreBuild` hook and I don't get error even if there is no cmake/autoconf files in the library.

**Comment by genotrance** [comment]
Will be great if you can add meson support with a PR. It's fairly simple.
