### ISSUE TITLE
[Need Help] Some problems encountered when trying to package Wolfssl library

### ISSUE THREAD

**Issue by darkr4y** [nimterop/nimterop#261]
I'm trying to package [Wolfssl](https://github.com/wolfSSL/wolfssl) with Nimterop. I've read the documentation and learned the basics of using Nimterop, and I've created a [Repo](https://github.com/darkr4y/nimwolfssl) to try to make Wolfssl as a library for Nim.
In the process, I encountered the following errors:

```
# Saved to C:/Users/dev/nimcache/nimterop/toastCache/nimterop_2966161807.nim
C:\Users\dev\Desktop\NimPlayground\nimwolfssl\nimwolfssl.nim(63, 8) template/generic instantiation of `cImport` from here
C:\Users\dev\.nimble\pkgs\nimterop-0.6.13\nimterop\cimport.nim(704, 10) template/generic instantiation of `cImport` from here
C:\Users\dev\nimcache\nimterop\toastCache\nimterop_2966161807.nim(813, 43) Error: undeclared identifier: 'CRITICAL_SECTION'
```

By searching Wolfssl's C code, as you can see that a macro definition needs to be passed [here](https://github.com/wolfSSL/wolfssl/blob/2ebb47ec32a05014e47e0e88ea8da8b42b1cf32a/wolfssl/wolfcrypt/wc_port.h) (`wolfssl/wolfcrypt/wc_port.h line 320`).
I try to use `cDefine()` or `{.passC.}` to define macro `"USE_WINDOWS_API"` and still get this error, all our friendly Nim community, please help me to solve this problem, BTW Im testing this on Windows and Nim version is 1.4.2, Nimterop version is 0.6.13.

**Comment by darkr4y** [comment]
I have updated the repo, I've tried to fill in some of the definitions from the Windows header files (eg Windows.h), it's strange that Nimterop doesn't handle it automatically.
And then I got the error below:

```
# Saved to C:/Users/dev/nimcache/nimterop/toastCache/nimterop_4156334578.nim
C:\Users\dev\Desktop\NimPlayground\nimwolfssl\nimwolfssl.nim(87, 8) template/generic instantiation of `cImport` from here
C:\Users\dev\nimcache\nimterop\toastCache\nimterop_4156334578.nim(1501, 39) Error: undeclared identifier: 'RsaKey'
```

After searching for wolfssl's code, I found that the definition about `RsaKey` is in the file `wolfssl/wolfcrypt/rsa.h`, Do I need to use `cImport` to include it?
I have also tried to use `cImport("wolfssl"/"wolfcrypt"/"rsa.h")`, but got another error below:

```
# Saved to C:/Users/dev/nimcache/nimterop/toastCache/nimterop_847371026.nim
C:\Users\dev\Desktop\NimPlayground\nimwolfssl\nimwolfssl.nim(87, 8) template/generic instantiation of `cImport` from here
C:\Users\dev\nimcache\nimterop\toastCache\nimterop_847371026.nim(873, 22) Error: undeclared identifier: 'mp_digit'
```

the definition `mp_digit` is in the file `wolfssl/wolfcrypt/integer.h`, I tried to import it in the same way, but the error remained.

**Comment by genotrance** [comment]
Let me give it a try later today, I'll get back with some suggestions.

**Comment by genotrance** [comment]
If you see the line where the error occurs in the wrapper:

```nim
MP_MASK* = (((cast[mp_digit](1)) shl
  typeof((cast[mp_digit](1)))((cast[mp_digit](DIGIT_BIT)))) -
  typeof((cast[mp_digit](1)))((cast[mp_digit](1))))
```

You are running into https://github.com/nimterop/nimterop/issues/206. You could either `cSkipOverride(@["MP_MASK"])` or use the suggestion in the last comment on that issue.

**Comment by darkr4y** [comment]
Thx for ur help, I'll try it and give a feedback soon ;)

**Comment by genotrance** [comment]
Things like these I just define as `type DRBG = object` and leave it. It only becomes relevant if you are using that symbol.

In many cases, you find such opaque symbols which don't really need detail in Nim since you won't use it directly.

Feel free to ping on the nimterop gitter channel if you want quicker responses.

**Comment by darkr4y** [comment]
I have updated my nimwolfssl repo, And I think it's ready to work.
But more testing is still needed, and I will use a full Wolfssl C/S example to determine if the wrapped code will work.
Maybe it's time to close this Issue, thanks again very much for your help, I learned a lot from this!
I will also do what I can to help others in Nim's(Nimterop) community.
Have a good day :)
