### ISSUE TITLE
header include guard translated into constant if followed by macro

### ISSUE THREAD

**Issue by royneary** [nimterop/nimterop#270]
I'm running toast (``toast --pnim --preprocess --output=test.nim test.h``) for a very simple header file:

``test.h``:
``` C
#ifndef TEST_H
#define TEST_H

#include "myheader.h"

MY_EXTERN void do_stuff();

#endif
```

``myheader.h``:
``` C
#ifndef MY_HEADER_H
#define MY_HEADER_H

#define MY_EXTERN

#endif
```

The resulting nim file is missing the function declaration, but instead contains an error message:

``` C
# const 'TEST_H' has unsupported value 'void do_stuff();'
```

The header include guard is translated into a constant (which fails on top).

Without the ``MY_EXTERN`` macro it works fine, but unfortunately the C library I'm trying to generate wrappers for uses a macro like that.

**Comment by genotrance** [comment]
You need to specify the include directory for preprocess. Try `-I`.
