### ISSUE TITLE
Whitespace in include folders breaks build

### ISSUE THREAD

**Issue by marcomq** [nimterop/nimterop#272]
When using windows and using a folder with whitespace in nimterop folder, the build fails.
Unfortunately, my windows home folder contained whitespace for unknown reasons, so choosenim also crashes during installation and I have no real workaround. 

I got following error messages when performing `nimble build` in a folder containing whitespace:
```
...
Building nimterop/nimterop/toast.exe using c backend
...
# Resetting C:\Users\Firstname Lastname\nimcache\nimterop\nimterop\treesitter_cpp
gcc.exe: error: Lastname\nimcache\nimterop\nimterop\treesitter\lib\include: No such file or directory
...
execution of an external compiler program 'C:\code\nim-1.4.4\dist\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -IC:\Users\Firstname Lastname\nimcache\nimterop\nimterop\treesitter\lib\include -IC:\Users\Firstname Lastname\nimcache\nimterop\nimterop\treesitter\lib\src -IC:\Users\Firstname Lastname\nimcache\nimterop\nimterop\treesitter_c\src -IC:\Users\Firstname Lastname\nimcache\nimterop\nimterop\treesitter_cpp\src -O3 -fno-strict-aliasing -fno-ident   -IC:\code\nim-1.4.4\lib -IC:\Users\Firstnam~1\AppData\Local\Temp\nimble_6212\githubcom_genotrancenimterop_0.6.12\nimterop -o "C:\Users\Firstname Lastname\nimcache\toast_r\lib.c.o" "C:\Users\Firstname Lastname\nimcache\nimterop\nimterop\treesitter\lib\src\lib.c"' failed with exit code: 1
```
The include folder direction `-Ifolder with whitespace` didn't use any quotes, so the whitespace made gcc expect a filename.
After adding surrounding double quotes `-I"folder with whitespace"` the build finishes without errors on my windows machine.

I created a PR for this to fix:

https://github.com/nimterop/nimterop/pull/271

Build succeeds on windows. Tests still do not work yet when having whitespace, but have no issues when using a folder without whitespace. So there might still some work to do to make it run without errors on folders with whitesapces. But I didn't want to change too much.

P.S.:
Do I need to open an issue or would it have been sufficient to create a PR?

**Comment by genotrance** [comment]
PR should be sufficient to track. Please fix all instances if you can. Thanks in advance.
