### ISSUE TITLE
[Question] Binding to OpenCV

### ISSUE THREAD

**Issue by WhoAteDaCake** [nimterop/nimterop#283]
Hi, was just wondering if anyone had made successful bindings to openCV using this library, I've been trying, but I keep getting: 

> /home/toshiba/.choosenim/toolchains/nim-1.6.0/lib/system/fatal.nim(53, 5) Error: unhandled exception: /home/toshiba/.nimble/pkgs/nimterop-0.6.13/nimterop/build/getheader.nim(238, 12) `buildStatus.built` 
Build configuration failed - No build files found in /home/toshiba/.cache/nim/nimterop/opencv2
 [AssertionDefect]

**Comment by genotrance** [comment]
OpenCV looks like C++, won't work with nimterop I don't think.

Usually you see that error if you haven't set the right `-d:` flags like `-d:opencvGit` or something.

**Comment by WhoAteDaCake** [comment]
Oh dammit, that's a shame
