### ISSUE TITLE
Using nimterop in MSYS2 Bash environment on Windows

### ISSUE THREAD

**Issue by michaelsbradleyjr** [nimterop/nimterop#284]
When developing with Nim on Windows over the last year+, my preferred setup (for compiling, etc.) has become a Bash shell in [MSYS2's UCRT64 environment](https://www.msys2.org/docs/environments/). It's nice because you get a very Linux-like experience while developing, but you're building native Windows programs.

Currently, I'm trying out nimterop for a project but have run into a snag on Windows (it's working fine on Linux and macOS). Consider these lines:

https://github.com/nimterop/nimterop/blob/master/nimterop/build/tools.nim#L209-L211

In an MSYS2 Bash shell, I do want `-G"MSYS Makefiles"`; but `sh -c uname -a` yields `MINGW64_NT-10.0-19043`, so nimterop instead invokes cmake with `-G"MinGW Makefiles"`, which hangs indefinitely. I'm not sure why it hangs, but that's the behavior I get on several Windows machines, including  Windows in GitHub Actions.

I can hack nimterop by changing L210 to:
```nim
if true: # uname.contains("msys"):
```
And it works: the cmake step no longer hangs.

I'm happy to submit a PR with a proper solution, but I'm not sure yet what's the best approach. Any ideas?

**Comment by genotrance** [comment]
Sorry it's been a while since I've done this but there might be a way to discriminate between MSYS and MinGW. Maybe the [MSYSTEM](https://stackoverflow.com/questions/37460073/msys-vs-mingw-internal-environment-variables) variable?

**Comment by michaelsbradleyjr** [comment]
Nice idea, maybe `$MSYSTEM` detection is the way to go. I tried `echo`'ing it in a Bash shell for various MSYS2 environments:
* `MSYS` environment, `$MSYSTEM` is `MSYS`
* `MINGW64` environment, `$MSYSTEM` is `MINGW64`
* `MINGW32` environment, `$MSYSTEM` is `MINGW32`
* `UCRT64` environment, `$MSYSTEM` is `UCRT64`
* ...

By default (at least when checking my own Win machines), `%MSYSTEM%` in cmd.exe is unset, and `$env:MSYSTEM` in PowerShell is unset.

So maybe it would be enough to check if it's set with `os` module's `existsEnv`? If so, use `-G"MSYS Makefiles"`; if not, use `-G"MinGW Makefile"`?

Would that logic be suitable to wholly replace the uname check in the `if findExe("sh").len != 0` branch of `when defined(Windows)`?

🤔 I feel like I'm probably not appreciating the fully variety of environmental conditions that could be in play, but not sure.

**Comment by genotrance** [comment]
I see you already clarified the MSYSTEM question here.
