### ISSUE TITLE
Name change proposal

### ISSUE THREAD

**Issue by zestyr** [nimterop/nimterop#33]
`toast` clashes with an ffmpeg dependency for GSM compression, so machines with an improperly setup path would cause nimterop to fail with a strange error message complaining about invalid arguments.

Maybe `c2ast` would be a fitting name? If nimterop plans to support more languages than C/C++ that would be inaccurate though. `astgen` or `genast` perhaps? `ast2nim`?

**Comment by genotrance** [comment]
Most of these might exist already - I think we might be better off going with `nimterop` itself since it is a quite unique name.

Open to feedback though.

**Comment by timotheecour** [comment]
anything starting with `nim` would be fine, eg `toast` => `nimteropast` (makes it clear it's related to `nimterop`)

**Comment by timotheecour** [comment]
not smthg ud type everyday so maybe nimteropcli

**Comment by genotrance** [comment]
Once toast is a relative path from cimport, this won't be needed anymore. We can keep the name toast.

**Comment by genotrance** [comment]
Toast is now a relative path for cimport so that won't fail. If user wants to use on command line and it clashes, he can now give full path. I don't think we need to rename anymore. Please close if you agree.

**Comment by zestyr** [comment]
Fine with me.

**Comment by timotheecour** [comment]
on the other hand it's probably not too hard to fix assuming we can rename the generated binary, see https://github.com/nimterop/nimterop/pull/70#issuecomment-458454003 for an approach
