### ISSUE TITLE
char** support

### ISSUE THREAD

**Issue by zestyr** [nimterop/nimterop#34]
`char**` can be mapped to the `cstringArray` type.

> `cstringArray {...} = ptr UncheckedArray[cstring]`
This is binary compatible to the type char** in C. The array's high value is large enough to disable bounds checking in practice. Use `cstringArrayToSeq` to convert it into a `seq[string]`.

**Comment by alaviss** [comment]
Can we also have support for pointer-of-pointer?

I'm wrapping `kmod` and they have functions like this:

```c
struct kmod_module;
int kmod_module_new_from_name(struct kmod_ctx *ctx, const char *name,
						struct kmod_module **mod);
```

These can be roughly mapped to

```nim
proc kmod_module_new_from_name*(ctx: ptr kmod_ctx; name: cstring; `mod`: var ptr kmod_module): int {.importc, header: headerlibkmod.}
```

**Comment by genotrance** [comment]
This has been implemented in the latest commit.

Considering there's no way to know what the developer meant with `char **` - could be array of cstring or pointer to a cstring, I'm just mapping everything to `ptr ptr`, except `ptr ptr cchar` which becomes `ptr cstring`. This was one of Araq's examples of how you cannot always translate 100% automatically.

@alaviss - your case will become `ptr ptr kmod_module`. This is how c2nim does it right now as well.

```nim
type
  kmod_module* {.bycopy.} = object

proc kmod_module_new_from_name*(ctx: ptr kmod_ctx, name: cstring, `mod`: ptr ptr kmod_module): cint {.importc, header: headertest.}
```

Open to feedback.
