### ISSUE TITLE
[minor] more readable generated nim wrappers

### ISSUE THREAD

**Issue by timotheecour** [nimterop/nimterop#60]
from https://ptpb.pw/-vx0/nim

```nim
proc svDpiVersion*(): cstring {.importc: "svDpiVersion", header: headersvdpi.}
proc svGetBitselBit*(s: ptr svBitVecVal; i: cint): svBit {.importc: "svGetBitselBit",
    header: headersvdpi.}
...
```

=>

```nim
{.push header: "headersvdpi".}
proc svDpiVersion*(): cstring {.importc: "$1".}
proc svGetBitselBit*(s: ptr svBitVecVal; i: cint): svBit {.importc: "$1".}
...
{.pop.}
```

**Comment by genotrance** [comment]
This isn't working due to some Nim bug.

```nim
  var fp = fullpath.replace("\\", "/")
  echo &"{{.push header: \"{fp}\".}}"
```

It gets echoed out fine by toast but after parseStmt, it becomes:

```nim
{.push, header: "/home/genotrance/Dropbox/Private/github/nimterop/tests/include/test.h".}
```

Note the comma that got added.

**Comment by timotheecour** [comment]
* fixed 1 part of this here: https://github.com/genotrance/nimterop/pull/70/commits/c0cf319d456e3d9718f5dbff71fc105770ea5fe4

* for 2nd part maybe this:
```
proc FreeImage_DeInitialise*() {.importc, header: headerFreeImage.}
=>

{.pragma nimteropImport: [importc, header: headerFreeImage].} # can add more stuff here if needed (more DRY!)
proc FreeImage_DeInitialise*() {.nimteropImport.}
```

**Comment by genotrance** [comment]
I don't see what this commit has to do with this issue? And what is the second part?

**Comment by timotheecour** [comment]
> I don't see what this commit has to do with this issue?

it does:
```
proc FreeImage_DeInitialise*() {.importc: "FreeImage_DeInitialise", header: headerFreeImage.}
=> my initial idea (as shown in top post in this issue)
proc FreeImage_DeInitialise*() {.importc: "$1", header: headerFreeImage.}
=> implementation in commit: remove `"$1"` altogether when name matches; it's just visual noise
proc FreeImage_DeInitialise*() {.importc, header: headerFreeImage.}
```

> And what is the second part?

2nd part was factoring out `header: headersvdpi.` which repeats everywhere; but for the 2nd part I'm now in favor of the (IMO cleaner) suggestion i gave above https://github.com/genotrance/nimterop/issues/60#issuecomment-457821387

**Comment by genotrance** [comment]
Sorry, this was unreadable on the phone and I misunderstood.

I like first one - will implement it but `nimteropImport` will be confusing, especially when interleaved with case 1. If we can get a fix for `{.push header: "x".}` through parseStmt, will be great. That's super clean.

**Comment by genotrance** [comment]
Pragmas are now cleaner in `pragma` branch.
