### ISSUE TITLE
generate informative doc comments from headers

### ISSUE THREAD

**Issue by timotheecour** [nimterop/nimterop#61]
nimterop should allow generating doc comments for each decl generated; and this could be customizable (eg via an enum)

* pretty sure treesitter exposes comments, so might as well use them to generate doc comments, that way we can have half decent (or more) docs for free

* doc comment could also specify the corresponding declaration from source function

* furthermore, w the plugin idea we discussed, a wrapper writer can provide his definition for a symbol inside `onSymbol(..)`, and can be creative about it in a way that'd be impossible for nimterop to handle, for eg:
* using doxygen
* custom weird formats like ncurses; not sure where doc comments are for symbols for ncurses ; maybe https://github.com/mirror/ncurses/blob/master/doc/ncurses-intro.doc ( see also https://invisible-island.net/ncurses/man/curs_printw.3x.html); 

*  @rnowley how did u insert doc comments in https://github.com/rnowley/nim-ncurses/blob/master/ncurses.nim ?

**Comment by genotrance** [comment]
We can look into this in the future.

**Comment by genotrance** [comment]
Right now, preprocessing strips out all comments. They can be brought back by using the `-CC` flag with `gcc` but handling them is a completely different challenge. Standalone comments could be handled but inline ones within structs and procs won't be trivial.

**Comment by genotrance** [comment]
Further thoughts - nimterop reorders and groups all consts, types and procs, completely changing everything. This is to handle forward declarations which Nim currently doesn't support. This means comments could be quite out of place in the resulting output.
