### ISSUE TITLE
[codegen] toast silently ignores things it can't handle in `define` statements

### ISSUE THREAD

**Issue by timotheecour** [nimterop/nimterop#75]
followup for https://gitlab.com/kaushalmodi/nimterop-throwaway-1 

discussed here: https://gitter.im/nimgen/Lobby?at=5c4e8af8f46373406a10a9d1
note: i had to add (on OSX): `cIncludeDir("/opt/X11/include/")` in `eggx.nim`

adding to eggx.h
```c
void foobar();
#define foobar2 123
```

will indeed show those procs

nim c EGGX/eggx.nim
```
{.passC: "-I/private/tmp/d41/nimterop-throwaway-1/draw/EGGX080".}

{.passC: "-I/opt/X11/include/".}
Importing /private/tmp/d41/nimterop-throwaway-1/draw/EGGX080/eggx.h
/Users/timothee/git_clone/nim/nimterop/build/toast --pnim --preprocess --includeDirs+=/private/tmp/d41/nimterop-throwaway-1/draw/EGGX080 --includeDirs+=/opt/X11/include/ /private/tmp/d41/nimterop-throwaway-1/draw/EGGX080/eggx.h

{.experimental: "codeReordering".}
const
  headereggx = "/private/tmp/d41/nimterop-throwaway-1/draw/EGGX080/eggx.h"
  foobar2* = 123
proc foobar*() {.importc, header: headereggx.}
```

however the rest doesnt show anything; i think it's an instance of this:

[option to give error upon encountering `Potentially invalid syntax` · Issue #9 · genotrance/nimterop](https://github.com/genotrance/nimterop/issues/9)

which is getting fixed soon (now that plugin PR merged)

~~so probably the issue is that `eggx_ggetdisplayinfo`(etc) is not visible~~

EDIT:
~~so the type of `eggx_ggetdisplayinfo` is `int (int *, int *, int *)` and nimterop can't handle it, but instead of giving a warning (or error) it silently skips~~

EDIT
things that helped me debug this:
```
toast --past
toast --pnim
```
eg:
```
$nim_D/nimterop/build/toast --past --preprocess=true --defines+=FORCE --includeDirs+=/opt/X11/include/ --includeDirs+=EGGX080 /tmp/d41/nimterop-throwaway-1/draw/EGGX080/eggx.hq
```

- [ ] would also help if `--past` had an option to show name of symbol eg in `(preproc_arg 56 16 4)` => should also show symbol name

**Comment by kaushalmodi** [comment]
- `eggx.h` has `#include <eggxlib.h>`, and
  - `eggxlib.h` has `#include <eggx_base.h>`

So:

- `cImport(cSearchPath("eggx.h"))` does not work (i.e. the Nim wrappers don't get generated)
- `cImport(cSearchPath("eggxlib.h"))` does not work (i.e. the Nim wrappers don't get generated)
- But `cImport(cSearchPath("eggx_base.h"))` does not work (works, but then I ended up with issue https://github.com/genotrance/nimterop/issues/76)

**Comment by timotheecour** [comment]
ok what's going on is following:
```
#define foo1 10 # works
#define foo2 10.0 # works
#define foo3 "abc" # BUG1 `string litteral` doesn't work (silently skips)
#define foo4 foo3 # BUG2 `symbol` doesn't work (silently skips)
```

## proposal1
* instead of silently skipping, call `onError(context: Context)` when it can't map a symbol instead of silently skipping (using same plugin mechanism)

## proposal2
BUG1 should be easily fixed by mapping to `const foo3 = "abc"`

## proposal3
beyond calling `onError()`,  for BUG2,  the closest would be a template:
map to 
```nim
template foo4*(): auto = foo3
```
but that won't work in some cases

this case is nastier because C allows pretty much anything and that's **legal** eg:
```c
#define foo whatever_that_does_not_exist
#define COMMA  ,
#define EXTERNC  extern "C"
#define BEGIN "{"
```

**Comment by genotrance** [comment]
Preprocessor macros for procs is already being tracked in https://github.com/genotrance/nimterop/issues/31.

Why do you want strings to get pulled into Nim? How exactly is it useful? You aren't going to pass those to procs as params.

**Comment by timotheecour** [comment]
> Why do you want strings to get pulled into Nim?

how is that different from int or float litterals? 
eg:
```
$homebrew_D/Cellar/opencv/4.0.1/include/opencv4/opencv2/flann/config.h:36:9:#define FLANN_VERSION_ "1.6.10"
boost/include/boost/version.hpp:30:1:#define BOOST_LIB_VERSION "1_68"
emscripten/libexec/llvm/include/llvm/Config/llvm-config.h:24:1:#define LLVM_DEFAULT_TARGET_TRIPLE "x86_64-apple-darwin18.2.0"
```

for more examples:
```
cd $homebrew_D/opt
rg -t h --follow '#define.*"' | less_fast
```

(a lot of entries)


string litterals is a case that we can faithfully map with 0 ambiguities (unlike `#define foo expr`), so might as well; it's useful in other contexts too eg source to source translation

**Comment by genotrance** [comment]
Numeric values often are used for constants, error codes, bitmasks and other stuff so I included those. Strings I left out because it isn't as often used as function parameters.

Meanwhile, `#define XYZ "12345"` is doable but `#define XYZ ABC` is a different category altogether. I'm okay with the former since you could of some if/then on them but I still wonder how useful it is at the Nim layer.

**Comment by genotrance** [comment]
Note also that toast intentionally translates only what it understands because it is searching the AST for known structures. It ignores what it doesn't know. We can warn about ERRORs in the AST but warning or erroring for unknowns will be a lot of chatter.

Unlike the c2nim approach where the parser is built-in and things not understood are failures, toast is more resilient and gives you at least functional results if partial. If something is missing and is material to the user, he can cOverride. He will only know something is missing if he cares. Otherwise, the wrapper is perfectly useful.
