### ISSUE TITLE
Incorrect Nim wrapper for "foo( const char *, ... );" signature [varargs support]

### ISSUE THREAD

**Issue by kaushalmodi** [nimterop/nimterop#76]
This issue is a spinoff of https://github.com/genotrance/nimterop/issues/75.

C Header:

```C
extern void eggx_gsetinitialparsegeometry( const char *, ... ) ;
```

Example invocation in C:

```C
/*
static int Gwin = 0;
*/

/*
..
*/

    eggx_gsetinitialparsegeometry("%+d%+d", Gwin * (200 + 10), 0);
```

Nim mapped code:

```nim
proc eggx_gsetinitialparsegeometry*(a1: cstring) {.
    importc: "eggx_gsetinitialparsegeometry", header: headereggx_base.}
```

What should that "..." in C code map to in Nim?

**Comment by kaushalmodi** [comment]
Steps to reproduce the issue:

1. Clone and checkout branch `nimterop-issue-76` from https://gitlab.com/kaushalmodi/nimterop-throwaway-1/tree/nimterop-issue-76/
2. cd to the draw dir
3. `nim c draw`

Error:

```
draw.nim(11, 32) Error: type mismatch: got <string, int32, int literal(0)>
but expected one of:
proc eggx_gsetinitialparsegeometry(a1: cstring)

expression: eggx_gsetinitialparsegeometry("%+d%+d", Gwin * 210, 0)
```

**Comment by kaushalmodi** [comment]
Nim wrapper generated right now:

```nim
proc eggx_gsetinitialparsegeometry*(a1: cstring) {.
    importc: "eggx_gsetinitialparsegeometry", header: headereggx_base.}
```

It should probably generate below (below is tested to work):

```nim
proc eggx_gsetinitialparsegeometry*(a: cstring) {.varargs,
                                             importc: "eggx_gsetinitialparsegeometry",
                                             header: headereggx_base.}
```

**Comment by timotheecour** [comment]
yes ; PR welcome!

**Comment by genotrance** [comment]
Tree-sitter doesn't provide me with this info so I've opened an issue with them. For now, you will have to `cOverride` such procs.

https://github.com/tree-sitter/tree-sitter-cpp/issues/31

**Comment by genotrance** [comment]
This is fixed in ast2.
