### ISSUE TITLE
[ast] option to give error upon encountering `Potentially invalid syntax` 

### ISSUE THREAD

**Issue by timotheecour** [nimterop/nimterop#9]
otherwise, easy to miss then leads to further odd-ness

**Comment by genotrance** [comment]
I think the current strategy to continue and wrap what is possible and let Nim catch missing portions is mostly working. Of course, if something gets missed and isn't referenced for Nim to check, it will only ever get detected when someone wants to use that particular type or proc and doesn't find it.

I'm not sure if this is something we want to implement as of yet but will continue to track for now.

**Comment by timotheecour** [comment]
actually, on 2nd thought, for this kind of thing a callback `onInvalidSyntax(...)` (which by default could be `nil`)  is much better approach

**Comment by genotrance** [comment]
Considering this is run by toast in an independent process, how would you even callback? You would have to recompile toast to add any action.

**Comment by timotheecour** [comment]
besides plugin-based via `dlopen`  (which is overkill here) how about:

toast_custom.nim:
```nim
import toast # toast library
proc onInvalidSyntax(context: Context) =
  doAssert false, $context
```

```
nim c toast_custom
nimterop --toast=toast_custom ...
```

**Comment by genotrance** [comment]
With the new plugin system, we can add an onError callback which can get called when an ERROR is encountered by tree-sitter.

We could also call it when nimterop runs into its own errors that currently call doAssert.

Would need an enum of error values and corresponding messages. Not crucial right now, some time in the future.

**Comment by genotrance** [comment]
Closing this - already wrappers are hard to deal with, I see almost no one interested in catching errors and reacting. In fact, these are only useful during development so I'd rather spend effort improving functionality and better error messages.
