### ISSUE TITLE
don't test with both `nim c -d:release toast` and `nim c toast` if users will just use `nim c toast`

### ISSUE THREAD

**Issue by timotheecour** [nimterop/nimterop#90]
## proposal 1 (ideal)
try to make `nimble install` install toast in a  way we can customize ~~via `-d:release`~~ [EDIT: -d:release is already implied] (maybe possible using `task setup`, `setupTask` and `before install`) which allows to
* move toast binary to build/toast instead of in source dirs
* ~~make nimterop wrapping faster for user code~~

## proposal 2 (alternative)
if proposal 1 doesn't work, it makes to sense to run test suite with both `nim c -d:release toast` and `nim c toast` , we shd just run it with `nim c toast` since that's what users will run their code with AND `-d:release` won't catch any more bugs

**Comment by genotrance** [comment]
Nimble install is -d:release.

**Comment by timotheecour** [comment]
> Nimble install is -d:release.

you're right, I was looking at `nimble build`, for which this isn't the case: 
```
# introduce a voluntary bug in toast.nim
nimble build -y
Command: "/Users/timothee/.nimble/bin/nim" c --noBabelPath --path:"/Users/timothee/git_clone/nim/nim-regex/src"  --path:"/Users/timothee/.nimble/pkgs/unicodedb-0.6.0"  --path:"/Users/timothee/.nimble/pkgs/unicodeplus-0.4.0"  --path:"/Users/timothee/.nimble/pkgs/unicodedb-0.6.0"  --path:"/Users/timothee/git_clone/nim/cligen"  -o:"/Users/timothee/git_clone/nim/nimterop/nimterop/toast" "/Users/timothee/git_clone/nim/nimterop/nimterop/toast.nim"
```

however, `nimble build` is the only choice if you're relying on a customized nimble pkg; 

this is actually a nimble limitation, that we can't pass `-d:release` or other nim flags as is to nimble (basically this is https://github.com/nim-lang/nimble/issues/599) 
(and the fact that we have to voluntarily crash nimble just to see what's being run, ie that --verbose isn't enough ...)

still, i don't think it makes sense to run test suite with both -d:release on and off
