### ISSUE TITLE
[minor] more DRY importc with `{.importc: “freeimage_$1”.}`

### ISSUE THREAD

**Issue by timotheecour** [nimterop/nimterop#94]
when wrapping libs it'll be common that each symbol is prefixed / postfixed by a fixed name eg freeimage; in this case user may want to remove all such common prefix/suffix in wrapper, eg:
```
proc foo(){.importc: “freeimage_foo” .}
proc bar(){.importc: “freeimage_bar” .}
```

## proposal
we can make resulting wrappers more DRY:
```
proc foo(){.importc: “freeimage_$1” .}
proc bar(){.importc: “freeimage_$1” .}
```

main benefit: 
It’s not just for DRY, it’s for human eye to focus on parts that require his attention (the occasial violation caused by a user-issued or nimterop issued custom rename) as opposed to the predictable (`freeimage_foo` => `foo`)

## implementation:
trivial, just find whether nimName is a prefix or suffix of origName in genImportC, see https://github.com/genotrance/nimterop/pull/88/files

**Comment by genotrance** [comment]
Should we instead add some standard symbol changes to plugin.nim? Remove _, remove prefix, remove suffix, etc. Then it is obvious when this $1 should be done.

**Comment by zestyr** [comment]
Removing prefix can be useful for cleaner code in some cases, but it should definitely be optional. MagickCore and MagickWand share a lot of function names, only prefixed with `Magick` for sane defaults.

**Comment by genotrance** [comment]
It would have to be user initiated since it will be part of the plugin system. I also feel the onSymbol method is heavy just to strip out _.

**Comment by genotrance** [comment]
Closing this issue - the pragmas are a lot smaller now and only elaborated if there's a change. Not exactly like this but good enough for the near-term.
